### ISSUE TITLE
Getting stunned breaks all animations

### ISSUE THREAD

**Issue by OscarAnderlind** [ltsLumina/FG-GP-Team1#76]
After getting stunned no other animation works

**Comment by turnercore** [comment]
I’ll look at this, it should be going back to the idle pose after stun but I think theees a not stunned trigger that is not being called when the stun is over. Make sure stun is being released for. Whatever script is stunning the player

**Comment by turnercore** [comment]
Ok I checked this and it must be in the code that is stunning the player, the animations are not affected at all right now by stun. There's only one animation going off stun trigger, and it has an exit time and only 4 frames of animation since it isn't in yet. In fact, basically stun SHOULD probably stop movement rotation and stuff and isn't. I don't know what script is actually stunning the player but it's probably like turning off the animation controller and not turning it back on
